config/routes.rb
Tremmel::Application.routes.draw do
  resources :blog, only: [:index]
  resources :posts, path: '/blog/posts', only: [] do
    resources :comments, only: [:index, :new, :create]
  end
  resources :posts, path: '/admin/posts' do
    resources :comments, only: [:index, :destroy] do
      collection do
        get :supervise
      end
    end
  end
  resources :admin, only: [:index]
  resources :usuario, only: [:index, :destroy, :new, :create], path: "/admin/usuarios"

  devise_for :users
  get "staticpage/index"
  post "staticpage/contactar"

  root 'staticpage#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, polymorphic: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, as: :commentable
	mount_uploader :imagen, ImagenUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout 'layouts/admin'
	before_filter :authenticate_user!

	def index
		#redirect_to :controller=>'posts', :action => 'index'
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) do |u|
 			u.permit(:nombre, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
	layout 'layouts/application'
  def index
  	@posts = Post.order("created_at DESC")
  	@posts_recientes = Post.order("created_at DESC")
  	@users = User.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  layout :dynamic_layout
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @post = Post.find(params[:post_id])
    @user = User.find(@post.user_id)
    @commentable = find_commentable
    @comments = @commentable.comments.order("created_at DESC")
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

   # GET /comments/supervise
  def supervise
    @post = Post.find(params[:post_id])
    @comments = @post.comments.order("created_at DESC")
  end

  # POST /comments
  # POST /comments.json
  def create
    @commentable = find_commentable
    @comment = @commentable.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to id: nil }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to supervise_post_comments_path(params.delete(:post_id)) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:nombre, :email, :web, :content, :commentable_id, :commentable_type)
    end

    def find_commentable  
      params.each do |name, value|  
        if name =~ /(.+)_id$/  
          return $1.classify.constantize.find(value)  
        end  
      end  
      nil  
    end

    def dynamic_layout
      if request.original_url.scan("admin").count == 1
        "layouts/admin"
      else
        "layouts/application"
      end    
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout :dynamic_layout
  before_filter :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(:created_at)
    @users = User.all
    
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    post = Post.find(params[:id])
    @user = User.find(post.user_id)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: nil }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: nil }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :contenido, :user_id, :publicar, :imagen, :imagen_cache)
    end

    def dynamic_layout
      puts request.original_url
      if request.original_url.scan("admin").count == 1
        "layouts/admin"
      end    
    end
end

app/controllers/staticpage_controller.rb
class StaticpageController < ApplicationController
  def index
  	@posts = Post.order("created_at DESC")
  	@users = User.all
  end

  def contactar
  	if verify_recaptcha( :message => "Oh! Error con el reCAPTCHA!")
    	ContactMailer.contact(params).deliver
  		redirect_to root_path(anchor: 'contactanos'), notice: params[:name]+', ¡Tu mensaje ha sido en enviado!'
		else
	    redirect_to root_path(anchor: 'contactanos'), alert: params[:name]+', ¡Error!'
		end
  end
end

app/controllers/usuario_controller.rb
class UsuarioController < ApplicationController
	layout 'layouts/admin'

  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to usuario_index_path, notice: 'user was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  	user = User.find(params[:id])
    user.destroy
    respond_to do |format|
      format.html { redirect_to usuario_index_path }
      format.json { head :no_content }
    end
  end
end

private

# Never trust parameters from the scary internet, only allow the white list through.
def user_params
  params.require(:user).permit(:nombre, :email, :password, :password_confirmation)
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/staticpage_helper.rb
module StaticpageHelper
end

app/helpers/usuario_helper.rb
module UsuarioHelper
end

app/views/blog/index.html.haml
- @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(3)
.container#blog
	.page-header
		%center
			%h3 BLOG
			.title-divisor
			%h1#title-large
				%span Nuestros Posts
				%span.punto> .
	.col-sm-8.col-md-8
		-	 @posts.each_with_index do |post, index|
			.row
				- if post.publicar
					.col-sm-12.col-md-12
						.thumbnail
							= link_to	(image_tag "#{post.imagen_url(:large).to_s}"), post_comments_path(post), "data-no-turbolink" => "true"
							.caption
								%h4
									= "#{post.titulo}"
								%small 
									= "#{@users.find(post.user_id).nombre}, #{post.created_at.strftime("%B %d, %Y")}"
								%p= "#{post.contenido.split(" ")[0..80].join(" ")}...".html_safe
								%div.read-more
									= link_to "Leer mas...", post_comments_path(post), "data-no-turbolink" => "true"
		.row
			%center
				= paginate @posts
	.row
		.col-sm-4.cold-md-12
			%h3.title-short Últimos Posts
			%ul.simple-link-list
				- @posts_recientes.first(6).each do |post|
					%li
						=link_to "<h6>#{post.titulo}</h6>".html_safe, post_comments_path(post), "data-no-turbolink" => "true"
			%h3.title-short Tweets
			.col-sm-4.cold-md-12.timeline
				%a.twitter-timeline{"data-dnt" => "true", "data-widget-id" => "430978242892165120", :href => "https://twitter.com/tremmelweb" } Tweets de "@tremmelweb"
%center
	%script{:async => "", :src => "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
	/ TREMMELBLOG
	%ins.adsbygoogle{"data-ad-client" => "ca-pub-5862778022302728", "data-ad-slot" => "5256367218", :style => "display:inline-block;width:728px;height:90px"}
	:javascript
		(adsbygoogle = window.adsbygoogle || []).push({});
	%br/
	
.col-xs-12.col-sm-12.col-md-12.col-lg-12{ style: "background-color: #2997ac; color: white; padding-top: 20px;"}
	%center 
		Todos los derechos reservados 2014. Desarrollado por
		%span
			%span{:style => "font-size: 16px; font-style: italic; font-weight: bold; font-family: 'Raleway', sans-serif;"} TREMMEL
	%br
	%br

:javascript 
	if (window.location.pathname == '/blog') {
		$('.top-nav .current').removeClass("current")
		$('.top-nav li').eq(5).addClass("current")
		$('.top-nav a').attr("class", "external")
		$('.top-nav a').attr("data-no-turbolink", "true")
		$('.pagination a').attr("data-no-turbolink", "true")
		$('.top-nav a').eq(0).attr("href", window.location.origin+"/#home")
		$('.top-nav a').eq(1).attr("href", window.location.origin+"/#somos")
		$('.top-nav a').eq(2).attr("href", window.location.origin+"/#servicios")
		$('.top-nav a').eq(3).attr("href", window.location.origin+"/#clientes")
		$('.top-nav a').eq(4).attr("href", window.location.origin+"/#equipo")
		$('.top-nav a').eq(6).attr("href", window.location.origin+"/#contactanos")
		$(".navbar").animate({opacity: '1', top: '0px'}, 500);
	}

	!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

app/views/comments/_form.html.haml
= form_for @comment do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nombre
    = f.text_field :nombre
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :web
    = f.text_field :web
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :commentable_id
    = f.number_field :commentable_id
  .field
    = f.label :commentable_type
    = f.text_field :commentable_type
  .actions
    = f.submit 'Save'

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b Nombre:
  = @comment.nombre
%p
  %b Email:
  = @comment.email
%p
  %b Web:
  = @comment.web
%p
  %b Content:
  = @comment.content
%p
  %b Commentable:
  = @comment.commentable_id
%p
  %b Commentable type:
  = @comment.commentable_type

= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path

app/views/comments/supervise.html.haml
.container
	-if @comments.count != 0
		.panel.panel-default
			.panel-heading= "Post ##{@post.id}, Listado de comentarios"
			.table-responsive
				%table.table
					%thead
						%tr
							%th #
							%th Nombre
							%th Email
							%th Web
							%th Fecha
							%th Comentario
							%th Acción
					%tbody
						- @comments.each	do |comment|
							%tr
								%td
									= comment.id
								%td
									= comment.nombre
								%td
									= comment.email
								%td
									= comment.web
								%td
									= comment.created_at
								%td
									= link_to "#{comment.content.split(" ")[0..10].join(" ")}...", "#", data: { toogle: "tooltip", title:"#{comment.content}", placement:"bottom"  }
								%td
									= link_to 'Destroy', post_comment_path(@post.id, comment.id), method: :delete, data: { confirm: 'Are you sure?' }
	-else
		.panel.panel-default
			.panel-heading= "Post ##{@post.id}, No hay comentarios"


:javascript
	$("a").tooltip()

app/views/layouts/admin.html.haml
%html
  %head
    %title Tremmel
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag    "admin", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "staticpage", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default{:role => "navigation"}
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %a.navbar-brand{:href => "#"} Tremmel
      / Collect the nav links, forms, and other content for toggling
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li.active
            =link_to "Crear Post", new_post_path
          %li
            =link_to "Mis Posts", "/admin/posts"
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to "Usuarios", usuario_index_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              = current_user.nombre
              %b.caret
            %ul.dropdown-menu
              %li
                %a{:href => "#"} Action
              %li
                %a{:href => "#"} Another action
              %li
                %a{:href => "#"} Something else here
              %li.divider
              %li
                = link_to "Sign out", destroy_user_session_path, :method => :delete
      / /.navbar-collapse
    = yield
    %br
  :javascript
    $('.ckeditor').ckeditor({
        // optional config
    });

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo, class: "form-control"%>
  </div>

  <br>
  <div class="field">
    <%= f.file_field :imagen %><br>
    <%= f.hidden_field :imagen_cache, class: "form-control"%>
  </div>

  <br>
  <div class="field">
    <%= f.label :contenido %><br>
    <%= f.text_area(:contenido, :class => 'ckeditor') %>
  </div>
  <br>
  <div class="field">
    <%= f.check_box :publicar%>
    <%= f.label "¿Desea publicar este artículo?" %>
  </div>
  <div class="field hidden">
    <%= f.label :user_id %><br>
    <%= f.text_field(:user_id, :value => "#{current_user.id}") %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Crear Post" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="Container">
	<h1>Editing post</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @post %> |
	<%= link_to 'volver', admin_index_path %>
</div>

app/views/posts/index.html.erb
<div class="container">

  <div class="panel panel-default">
  <!-- Default panel contents -->
    <div class="panel-heading">Listado de Posts</div>

    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Título</th>
          <th>Autor</th>
          <th>¿Publicado?</th>
          <th>Fecha de publicación</th>
          <th>Acciones</th>
        </tr>
      </thead>

      <tbody>
        <% @posts.each do |post| %>
          <%- if post.user_id == current_user.id %>
            <tr>
              <td><%= post.id %></td>
              <td><%= post.titulo %></td>
              <td><%= @users.find(post.user_id).nombre %></td>
              <% if post.publicar %>
                <td><span class="glyphicon glyphicon-ok-circle"></span></td>
              <% else %>
                <td><span class="glyphicon glyphicon-remove-circle"></span></td>
              <% end %>
              <td><%= post.created_at.strftime("%B %d, %Y")%></td>
              <td><%= link_to 'Show', post %> | <%= link_to 'Edit', edit_post_path(post) %> | <%= link_to "Comentarios", supervise_post_comments_path(post) %> | <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= link_to 'volver', admin_index_path %>

</div>

app/views/posts/new.html.erb
<div class="container">
	<h1>New post</h1>

	<%= render 'form' %>

	<%= link_to 'volver', admin_index_path %>
</div>

app/views/staticpage/index.html.haml
#home
	.background-home
		.row.hidden-xs.hidden-sm{style:"margin-right: 0px;"}
			.col-md-6
				.logo-header-home.no-active
					%a{href: "#somos"}	
						%img{src: "assets/LogoTremmel.png"}
		.row.titles
			.col-md-12.visible-xs.visible-sm
				%center
					.link-scroll.no-active				
						%a{href: "#somos"}
							.scroll-welcome
								%img{src: "assets/scroll-welcome.png"}
							.scroll-down
								%img{src: "assets/logo2_welcome.png"}
			.col-md-12
				%center    
					.title-home
						%h1
							TREMMEL
				.col-md-12
					%center
						.divisor
				.col-md-12
					.v-carousel-mask
						%ul
							%li
								%h2 
									Turismo
									%span{style:"color:#66cc00;"}+ 
									Tecnología
									%span{style:"color:#66cc00;"}>.
							%li 
								%h2 
									Marketing Turístico
									%span{style:"color:#66cc00;"}>.
							%li 
								%h2 
									Posicionamos tu Marca
									%span{style:"color:#66cc00;"}>.
		#green-bar.visible-lg.visible-md
			.row.icons-home.hidden-xs#top-nav
				.col-md-2
					%center
						%a{href:"#servicios"}
							%i.fa.fa-cogs.icon#icon1
								%p Servicios
				.col-md-2
					%center							
						%a{ href:"#somos"}
							%i.fa.fa-bullseye.icon#icon2
								%p Nosotros
				.col-md-2
					%center
						%a{href:"#clientes"}
							%i.fa.fa-briefcase.icon#icon3
								%p Clientes
				.col-md-2
					%center
						%a{href:"#equipo"}
							.icon#icon4
								%div{style:"padding-top: 70px;"}
									%p Team
				.col-md-2
					%center
						%a{href:"#blog"}
							%i.fa.fa-book.icon#icon5
								%p Blog
				.col-md-2
					%center
						%a{href:"#contactanos"}
							%i.fa.fa-map-marker.icon#icon6
								%p Contáctanos

#servicios
	#background-servicios.seccion
		.page-header
			%center
				%h3{style:'color:white;'} SERVICIOS
				.title-divisor
				%h1#title-large
					%span.punto ¿
					%span> QUÉ HACEMOS EN TREMMEL
					%span.punto> ?
		%center
			%h4.text-servicios-1
				Damos soluciones digitales para potenciar el turismo.

		%br
		%br	
		.row
			.col-md-4
				%center
					.item-servicio
						%a{:href => "", "data-target" => "#modalcreativo", "data-toggle" => "modal"} 	
							.servicio-img#img-creativo
								=image_tag "turismocreativo.png" , id: "turismocreativo"
						%h3
							TURISMO CREATIVO	
						%p 
							Llevamos el diseño gráfico al turismo para acentuar y despertar el interés de tus clientes. Impacta y provoca en el turista la sensación de vivir una experiencia. 
			.col-md-4
				%center
					.item-servicio
						%a{:href => "", "data-target" => "#modaldigital", "data-toggle" => "modal"} 
							.servicio-img#img-digital
								=image_tag "turismodigital.png" , id: "turismodigital"
						%h3
							TURISMO DIGITAL	
						%p 
							Estar presente en redes sociales hoy en día es muy beneficioso para las empresas turísticas. Humaniza tu marca, acércate a tus clientes, la interacción es factor.
			.col-md-4
				%center
					.item-servicio	
						%a{:href => "", "data-target" => "#modalinteligente", "data-toggle" => "modal"} 					
							.servicio-img#img-inteligente
								=image_tag "turismointeligente.png", id: "turismointeligente"
						%h3
							TURISMO INTELIGENTE						
						%p 
							Aumenta tu alcance y posicionate en internet con nuestras aplicaciones de última tecnología. Hacemos más que páginas web, diseñamos extensiones de tu empresa en internet.

			
			

#somos.seccion
	.page-header
		%center
			%h3 ACERCA DE NOSOTROS
			.title-divisor
			%h1#title-large
				%span.punto ¿
				%span> POR QUÉ ELEGIR TREMMEL
				%span.punto> ?

			%br
			%h3 El turismo y la tecnología son nuestras pasiones
			
	.row#textoSomos{ style:"margin: 0px;"}
		.col-md-4{style: "margin-bottom:40px"}
			%center
				=image_tag "about-1.jpg",width: "100%", id:"img-somos"
		.col-md-4{style: "margin-bottom:30px"}
			.container.text-somos
				%p
					La información ayuda al turista a tomar decisiones en la selección de su destino, hotel o posada, ruta de viaje, restaurante, establecimientos, en fin, la mayoría de los servicios por no decir todos, y la interacción se torna cada vez más vital para esa toma de decisiones, donde la tecnología juega un papel importante, y ese “feedback” entre el turista y la empresa les permitirá a los prestadores de servicios: mejorar y destacarse.
				%center
					= image_tag "Tremmel-somos.png", id:"logo-about"

		.col-md-4{style: "margin-bottom:40px"}
			%center
				=image_tag "about-2.jpg",width: "100%"	, id:"img-somos"



= render template: "layouts/clientes"

= render template: "layouts/equipo"


- @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(6)
.container#blog
	.col-sm-12.col-md-12
		.page-header
			%center
				%h3 BLOG
				.title-divisor
				%h1#title-large
					%span POSTS RECIENTES
					%span.punto> .
		-	 @posts.each_with_index do |post, index|
			- if index.modulo(3) == 0
				.row
			- if post.publicar
				.col-sm-4.col-md-4{ style:"padding-left: 0px; padding-right: 0px;"}
					.thumbnail
						= link_to	(image_tag "#{post.imagen_url(:small).to_s}"), post_comments_path(post)
						.caption
							%h4
								= "#{post.titulo}"
							%small 
								= "#{@users.find(post.user_id).nombre}, #{post.created_at.strftime("%B %d, %Y")}"
							%p= "#{post.contenido.split(" ")[0..40].join(" ")}...".html_safe
							%div.read-more
								= link_to "Leer mas...", post_comments_path(post)
.footer
	.show-more-cube
		= link_to "<span>Mas Posts</span>".html_safe, blog_index_path()


//contacto
= render template: "layouts/contacto"

//Modals
= render template: "layouts/modaldigital"
= render template: "layouts/modalinteligente"
= render template: "layouts/modalcreativo"


:javascript
	$(function(){
    
		$.fn.center = function () {
			this.css("position","absolute");
			this.css("top", ( $(window).height() - this.height() ) / 2  + "px");
			this.css("left", ( $(window).width() - this.width() ) / 2 + "px");
			return this;
		}

		$(".titles").center();

		$(window).resize(function(){ // whatever the screen size this
			$(".titles").center();       // this will make it center when 
		});                          // window resize happens  
	});

	$( "#img-inteligente" ).hover(
		function() {
			$("#turismointeligente").css("display", "none")
		  $("#turismointeligente").attr("src","assets/turismointeligente_hover.png")
		  $("#turismointeligente").fadeIn(400);

		}, function() {
			$("#turismointeligente").css("display", "none")
		  $("#turismointeligente").attr("src","assets/turismointeligente.png")
		  $("#turismointeligente").fadeIn(400);
		}
	);
	$( "#img-creativo" ).hover(
		function() {
			$("#turismocreativo").css("display", "none")
			$("#turismocreativo").attr("src","assets/turismocreativo_hover.png")
			$("#turismocreativo").fadeIn(400);
		}, function() {
			$("#turismocreativo").css("display", "none")
			$("#turismocreativo").attr("src","assets/turismocreativo.png")
			$("#turismocreativo").fadeIn(400);
		}
	);
	$( "#img-digital" ).hover(
		function() {
			$("#turismodigital").css("display", "none")
			$("#turismodigital").attr("src","assets/turismodigital_hover.png")
			$("#turismodigital").fadeIn(400);
		}, function() {
			$("#turismodigital").css("display", "none")
			$("#turismodigital").attr("src","assets/turismodigital.png")
			$("#turismodigital").fadeIn(400);
		}
	);

app/views/usuario/index.html.haml
.container
	.panel.panel-default
		.panel-heading 
			=link_to "<span class='glyphicon glyphicon-plus'></span><span class'glyphicon-class></span> Usuario".html_safe, new_usuario_path, class: "btn btn-default"
		%table.table
			%thead
				%tr
					%th #
					%th Nombre
					%th email
					%th Eliminar
			%tbody
				- @users.each do |user|
					%tr
						%td= user.id
						%td= user.nombre
						%td= user.email
						%td= link_to "Eliminar", usuario_path(user.id), method: :delete, data: { confirm: "You sure?" }

	= link_to 'volver', admin_index_path